import keyboard
import time
input("Please push the button Enter")
time.sleep(4)
events = keyboard.write("Please push the button Enter")
time.sleep(4)
events = keyboard.write("Please push the button Enter")
time.sleep(4)
events = keyboard.write("Please push the button Enter")
time.sleep(4)
events = keyboard.write("Please push the button Enter")
time.sleep(4)
events = keyboard.write("Please push the button Enter")
time.sleep(4)
events = keyboard.write("Please push the button Enter")
